server:
  port: ${SERVER_PORT}

spring:
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ticketdb_api_prod

logging:
level:
org.springframework.data.mongodb.core: DEBUG

jwt:
  secret: ${SECRET_TOKEN}
